### ISSUE TITLE
Should be able to display a base64 image

### ISSUE THREAD

**Issue by evlach** [eclipse/streamsheets#33]
## Summary

Should be possible to display a base64 image on a sheet

...

## Motivation

Example scenario I met that: a cralwer sending messages incl urls and screenshoots. In general, as part of a message a service might send base64 images. Same of course for REST and other consumers / requestors.

...

## Additional context

...

**Comment by rejuce** [comment]
actuall it does...but its not documented yet... got it to work  by prepeding some text to the base64 encoded png image

CONCAT("data:image/png;base64,",G3) where G3 holds the base64 image

**Comment by TizianCedalo** [comment]
Thank you for this question!
I have added a documentation for adding base64 [images](https://docs.cedalo.com/streamsheets/2.4/tutorials/appbuilding/#images).



In older versions you will have to still use the [FILLPATTERN()](https://docs.cedalo.com/streamsheets/2.4/functions/shape/fillpattern) function and add it in the fill parameter of the DRAW() function.
