### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by fknipp** [eclipse/streamsheets#58]
### Description

README.md points to a file CONTRIBUTING.md, which is missing.

### Steps to Reproduce

1. Open https://github.com/eclipse/streamsheets#want-to-contribute-to-streamsheets
2. Click on the link CONTRIBUTING.md

**Expected behavior:**

A file containing informations how to contribute should be shown.

**Actual behavior:**

Error 404 File not found

**Reproduces how often:**

Always.

### Versions

N/A

### Additional Information

N/A

**Comment by cleancoderocker** [comment]
Just added a CONTRIBUTING.md.
