### ISSUE TITLE
Have you considered internationalization？

### ISSUE THREAD

**Issue by charliexp** [eclipse/streamsheets#68]
## Summary

...

## Motivation

...

## Additional context

...

**Comment by cleancoderocker** [comment]
Yes, we already support i18n. Currently only English and German are provided out of the box, but it is very easy to add other languages as well.

- For the Web UI there are two files `en.json` and `de.json` under `packages/webui/src/languages/`. They are loaded by the `translations.js` file in the same folder. For new languages you just need to add the language file and load it in `translations.js`. 
- The inline help for functions also supports i18n. Here the translations can be configured using the `help.js` files (e.g., `packages/functions/src/functions/math/help.js`.

We are happy to integrate other languages ​​and look forward to your pull request 😊
